import type { Question } from './route';


export const baseQuestions: Question[] = [
    { es: "Yo __ español todos los días.", en: "I speak Spanish every day.", answer: "hablo", tense: "pres" },
    { es: "Tú __ en casa hoy.", en: "You eat at home today.", answer: "comes", tense: "pres" },
    { es: "Ella __ en el centro.", en: "She works downtown.", answer: "trabaja", tense: "pres" },
    { es: "Nosotros __ en Madrid.", en: "We live in Madrid.", answer: "vivimos", tense: "pres" },
    { es: "Vosotros __ rápido.", en: "You all study quickly.", answer: "estudiáis", tense: "pres" },
    { es: "Ellos __ la música.", en: "They listen to the music.", answer: "escuchan", tense: "pres" },
    { es: "¿Tú __ agua?", en: "Do you drink water?", answer: "bebes", tense: "pres" },
    { es: "Yo __ una carta ahora.", en: "I write a letter now.", answer: "escribo", tense: "pres" },
    { es: "Ayer yo __ pan.", en: "Yesterday I bought bread.", answer: "compré", tense: "pret" },
    { es: "Ella __ temprano.", en: "She ate early.", answer: "comió", tense: "pret" },
    { es: "Nosotros __ en Sevilla.", en: "We traveled in Seville.", answer: "viajamos", tense: "pret" },
    { es: "Vosotros __ la puerta.", en: "You all opened the door.", answer: "abristeis", tense: "pret" },
    { es: "Ellos __ mucho.", en: "They worked a lot.", answer: "trabajaron", tense: "pret" },
    { es: "¿Tú __ a tiempo?", en: "Did you arrive on time?", answer: "llegaste", tense: "pret" },
    { es: "Yo __ en casa.", en: "I studied at home.", answer: "estudié", tense: "pret" },
    { es: "Ella __ allí un año.", en: "She lived there for a year.", answer: "vivió", tense: "pret" },
    { es: "Cuando era niño, yo __ mucho.", en: "When I was a child, I played a lot.", answer: "jugaba", tense: "imp" },
    { es: "Ella __ en la cafetería.", en: "She used to eat in the cafeteria.", answer: "comía", tense: "imp" },
    { es: "Nosotros __ cerca.", en: "We used to live nearby.", answer: "vivíamos", tense: "imp" },
    { es: "Vosotros __ siempre.", en: "You all used to study always.", answer: "estudiabais", tense: "imp" },
    { es: "Ellos __ música.", en: "They used to listen to music.", answer: "escuchaban", tense: "imp" },
    { es: "Yo __ en ese trabajo.", en: "I used to work in that job.", answer: "trabajaba", tense: "imp" },
    { es: "¿Tú __ agua todos los días?", en: "Did you use to drink water every day?", answer: "bebías", tense: "imp" },
    { es: "Ella __ cartas.", en: "She used to write letters.", answer: "escribía", tense: "imp" },
    { es: "Mañana yo __ a Sevilla.", en: "Tomorrow I will travel to Seville.", answer: "viajaré", tense: "fut" },
    { es: "Ella __ después.", en: "She will eat later.", answer: "comerá", tense: "fut" },
    { es: "Nosotros __ allí.", en: "We will live there.", answer: "viviremos", tense: "fut" },
    { es: "Vosotros __ la tarea.", en: "You all will study the homework.", answer: "estudiaréis", tense: "fut" },
    { es: "Ellos __ temprano.", en: "They will arrive early.", answer: "llegarán", tense: "fut" },
    { es: "Yo __ una carta.", en: "I will write a letter.", answer: "escribiré", tense: "fut" },
    { es: "¿Tú __ pan?", en: "Will you buy bread?", answer: "comprarás", tense: "fut" },
    { es: "Él __ en la oficina.", en: "He will work in the office.", answer: "trabajará", tense: "fut" },
    { es: "Yo __ más si tuviera tiempo.", en: "I would travel more if I had time.", answer: "viajaría", tense: "cond" },
    { es: "¿Tú __ ayudarme?", en: "Would you help me?", answer: "ayudarías", tense: "cond" },
    { es: "Ella __ aquí.", en: "She would eat here.", answer: "comería", tense: "cond" },
    { es: "Nosotros __ en la costa.", en: "We would live on the coast.", answer: "viviríamos", tense: "cond" },
    { es: "Vosotros __ hoy.", en: "You all would work today.", answer: "trabajaríais", tense: "cond" },
    { es: "Ellos __ temprano.", en: "They would arrive early.", answer: "llegarían", tense: "cond" },
    { es: "Yo __ la carta.", en: "I would write the letter.", answer: "escribiría", tense: "cond" },
    { es: "¿Tú __ pan?", en: "Would you buy bread?", answer: "comprarías", tense: "cond" },
    { es: "Yo __ hoy.", en: "I have worked today.", answer: "he trabajado", tense: "presperf" },
    { es: "¿Tú __ ya?", en: "Have you eaten yet?", answer: "has comido", tense: "presperf" },
    { es: "Ella __ mucho.", en: "She has studied a lot.", answer: "ha estudiado", tense: "presperf" },
    { es: "Nosotros __ en Madrid.", en: "We have lived in Madrid.", answer: "hemos vivido", tense: "presperf" },
    { es: "Vosotros __ a Italia.", en: "You all have traveled to Italy.", answer: "habéis viajado", tense: "presperf" },
    { es: "Ellos __ temprano.", en: "They have arrived early.", answer: "han llegado", tense: "presperf" },
    { es: "Yo __ pan.", en: "I have bought bread.", answer: "he comprado", tense: "presperf" },
    { es: "Él __ la música.", en: "He has listened to the music.", answer: "ha escuchado", tense: "presperf" },
    { es: "Yo __ cuando llegaste.", en: "I had studied when you arrived.", answer: "había estudiado", tense: "plup" },
    { es: "Ella __ antes de salir.", en: "She had eaten before leaving.", answer: "había comido", tense: "plup" },
    { es: "Nosotros __ allí dos años.", en: "We had lived there for two years.", answer: "habíamos vivido", tense: "plup" },
    { es: "Vosotros __ a tiempo.", en: "You all had arrived on time.", answer: "habíais llegado", tense: "plup" },
    { es: "Ellos __ mucho.", en: "They had worked a lot.", answer: "habían trabajado", tense: "plup" },
    { es: "Yo __ a México.", en: "I had traveled to Mexico.", answer: "había viajado", tense: "plup" },
    { es: "¿Tú __ ya?", en: "Had you drunk already?", answer: "habías bebido", tense: "plup" },
    { es: "Él __ la música.", en: "He had listened to the music.", answer: "había escuchado", tense: "plup" },
    { es: "Para mañana yo __ el examen.", en: "By tomorrow I will have studied for the exam.", answer: "habré estudiado", tense: "futperf" },
    { es: "¿Tú __ antes de llegar?", en: "Will you have eaten before arriving?", answer: "habrás comido", tense: "futperf" },
    { es: "Ella __ allí diez años.", en: "She will have lived there ten years.", answer: "habrá vivido", tense: "futperf" },
    { es: "Nosotros __ suficiente.", en: "We will have studied enough.", answer: "habremos estudiado", tense: "futperf" },
    { es: "Vosotros __ temprano.", en: "You all will have arrived early.", answer: "habréis llegado", tense: "futperf" },
    { es: "Ellos __ la casa.", en: "They will have bought the house.", answer: "habrán comprado", tense: "futperf" },
    { es: "Yo __ mucho.", en: "I will have traveled a lot.", answer: "habré viajado", tense: "futperf" },
    { es: "Él __ agua.", en: "He will have drunk water.", answer: "habrá bebido", tense: "futperf" },
    { es: "Yo __ pero estaba enfermo.", en: "I would have traveled but I was sick.", answer: "habría viajado", tense: "condperf" },
    { es: "¿Tú __ más?", en: "Would you have eaten more?", answer: "habrías comido", tense: "condperf" },
    { es: "Ella __ allí.", en: "She would have lived there.", answer: "habría vivido", tense: "condperf" },
    { es: "Nosotros __ antes.", en: "We would have studied earlier.", answer: "habríamos estudiado", tense: "condperf" },
    { es: "Vosotros __ temprano.", en: "You all would have arrived early.", answer: "habríais llegado", tense: "condperf" },
    { es: "Ellos __ la casa.", en: "They would have bought the house.", answer: "habrían comprado", tense: "condperf" },
    { es: "Yo __ mucho.", en: "I would have worked a lot.", answer: "habría trabajado", tense: "condperf" },
    { es: "Él __ la música.", en: "He would have listened to the music.", answer: "habría escuchado", tense: "condperf" },
    { es: "Espero que tú __.", en: "I hope you study.", answer: "estudies", tense: "subpres" },
    { es: "Es posible que él __ aquí.", en: "It's possible that he eats here.", answer: "coma", tense: "subpres" },
    { es: "Quiero que nosotros __ juntos.", en: "I want us to live together.", answer: "vivamos", tense: "subpres" },
    { es: "Dudo que ellos __ tarde.", en: "I doubt they arrive late.", answer: "lleguen", tense: "subpres" },
    { es: "Ojalá tú __ hoy.", en: "Hopefully you work today.", answer: "trabajes", tense: "subpres" },
    { es: "Recomiendo que vosotros __ más.", en: "I recommend you all study more.", answer: "estudiéis", tense: "subpres" },
    { es: "Es bueno que ella __ la carta.", en: "It's good that she writes the letter.", answer: "escriba", tense: "subpres" },
    { es: "Quería que tú __.", en: "I wanted you to study.", answer: "estudiaras", tense: "subimp" },
    { es: "Si yo __ tiempo, estudiara más.", en: "If I worked, I would study more.", answer: "trabajara", tense: "subimp" },
    { es: "Era importante que él __.", en: "It was important that he eat.", answer: "comiera", tense: "subimp" },
    { es: "Dudaban que nosotros __ allí.", en: "They doubted we lived there.", answer: "viviéramos", tense: "subimp" },
    { es: "Ojalá yo __ hoy.", en: "I wish I worked today.", answer: "trabajara", tense: "subimp" },
    { es: "Recomendé que vosotros __.", en: "I recommended that you all arrive.", answer: "llegarais", tense: "subimp" },
    { es: "Quería que ella __.", en: "I wanted her to write.", answer: "escribiera", tense: "subimp" },
    { es: "Me alegra que tú __.", en: "I'm glad you have arrived.", answer: "hayas llegado", tense: "subperf" },
    { es: "Es posible que él __.", en: "It's possible he has eaten.", answer: "haya comido", tense: "subperf" },
    { es: "Dudo que ellos __.", en: "I doubt they have lived there.", answer: "hayan vivido", tense: "subperf" },
    { es: "Espero que vosotros __.", en: "I hope you all have studied.", answer: "hayáis estudiado", tense: "subperf" },
    { es: "No creo que ella __.", en: "I don't think she has worked.", answer: "haya trabajado", tense: "subperf" },
    { es: "Es bueno que nosotros __.", en: "It's good that we have traveled.", answer: "hayamos viajado", tense: "subperf" },
    { es: "Me sorprende que tú __.", en: "It surprises me that you have drunk.", answer: "hayas bebido", tense: "subperf" },
    { es: "Me alegró que tú __.", en: "I was glad you had arrived.", answer: "hubieras llegado", tense: "subplup" },
    { es: "Si nosotros __, habríamos aprobado.", en: "If we had studied, we would have passed.", answer: "hubiéramos estudiado", tense: "subplup" },
    { es: "Dudaba que él __.", en: "I doubted he had eaten.", answer: "hubiera comido", tense: "subplup" },
    { es: "Ojalá vosotros __ allí.", en: "I wish you all had lived there.", answer: "hubierais vivido", tense: "subplup" },
    { es: "No creían que ella __.", en: "They didn't believe she had worked.", answer: "hubiera trabajado", tense: "subplup" },
    { es: "Era posible que yo __.", en: "It was possible that I had traveled.", answer: "hubiera viajado", tense: "subplup" },
    { es: "Me molestó que ellos __.", en: "It bothered me that they had arrived.", answer: "hubieran llegado", tense: "subplup" }
  ];
  //export default baseQuestions;