import type { Question } from './route';


export const baseQuestions: Question[] = [
    { es: "Yo __ español todos los días.", en: "I speak Spanish every day.", fr: "Je parle espagnol tous les jours.", answer: "hablo", tense: "pres", inf: "hablar" },
    { es: "Tú __ en casa hoy.", en: "You eat at home today.", fr: "Tu manges à la maison aujourd'hui.", answer: "comes", tense: "pres", inf: "comer" },
    { es: "Ella __ en el centro.", en: "She works downtown.", fr: "Elle travaille au centre-ville.", answer: "trabaja", tense: "pres", inf: "trabajar" },
    { es: "Nosotros __ en Madrid.", en: "We live in Madrid.", fr: "Nous vivons à Madrid.", answer: "vivimos", tense: "pres", inf: "vivir" },
    { es: "Vosotros __ rápido.", en: "You all study quickly.", fr: "Vous étudiez rapidement.", answer: "estudiáis", tense: "pres", inf: "estudiar" },
    { es: "Ellos __ la música.", en: "They listen to the music.", fr: "Ils écoutent la musique.", answer: "escuchan", tense: "pres", inf: "escuchar" },
    { es: "¿Tú __ agua?", en: "Do you drink water?", fr: "Tu bois de l'eau ?", answer: "bebes", tense: "pres", inf: "beber" },
    { es: "Yo __ una carta ahora.", en: "I write a letter now.", fr: "J'écris une lettre maintenant.", answer: "escribo", tense: "pres", inf: "escribir" },
    { es: "Ayer yo __ pan.", en: "Yesterday I bought bread.", fr: "Hier j'ai acheté du pain.", answer: "compré", tense: "pret", inf: "comprar" },
    { es: "Ella __ temprano.", en: "She ate early.", fr: "Elle a mangé tôt.", answer: "comió", tense: "pret", inf: "comer" },
    { es: "Nosotros __ en Sevilla.", en: "We traveled in Seville.", fr: "Nous avons voyagé à Séville.", answer: "viajamos", tense: "pret", inf: "viajar" },
    { es: "Vosotros __ la puerta.", en: "You all opened the door.", fr: "Vous avez ouvert la porte.", answer: "abristeis", tense: "pret", inf: "abrir" },
    { es: "Ellos __ mucho.", en: "They worked a lot.", fr: "Ils ont beaucoup travaillé.", answer: "trabajaron", tense: "pret", inf: "trabajar" },
    { es: "¿Tú __ a tiempo?", en: "Did you arrive on time?", fr: "Es-tu arrivé à l'heure ?", answer: "llegaste", tense: "pret", inf: "llegar" },
    { es: "Yo __ en casa.", en: "I studied at home.", fr: "J'ai étudié à la maison.", answer: "estudié", tense: "pret", inf: "estudiar" },
    { es: "Ella __ allí un año.", en: "She lived there for a year.", fr: "Elle a vécu là-bas pendant un an.", answer: "vivió", tense: "pret", inf: "vivir" },
    { es: "Cuando era niño, yo __ mucho.", en: "When I was a child, I played a lot.", fr: "Quand j'étais enfant, je jouais beaucoup.", answer: "jugaba", tense: "imp", inf: "jugar" },
    { es: "Ella __ en la cafetería.", en: "She used to eat in the cafeteria.", fr: "Elle mangeait à la cafétéria.", answer: "comía", tense: "imp", inf: "comer" },
    { es: "Nosotros __ cerca.", en: "We used to live nearby.", fr: "Nous vivions à proximité.", answer: "vivíamos", tense: "imp", inf: "vivir" },
    { es: "Vosotros __ siempre.", en: "You all used to study always.", fr: "Vous étudiiez toujours.", answer: "estudiabais", tense: "imp", inf: "estudiar" },
    { es: "Ellos __ música.", en: "They used to listen to music.", fr: "Ils écoutaient de la musique.", answer: "escuchaban", tense: "imp", inf: "escuchar" },
    { es: "Yo __ en ese trabajo.", en: "I used to work in that job.", fr: "Je travaillais dans ce travail.", answer: "trabajaba", tense: "imp", inf: "trabajar" },
    { es: "¿Tú __ agua todos los días?", en: "Did you use to drink water every day?", fr: "Tu buvais de l'eau tous les jours ?", answer: "bebías", tense: "imp", inf: "beber" },
    { es: "Ella __ cartas.", en: "She used to write letters.", fr: "Elle écrivait des lettres.", answer: "escribía", tense: "imp", inf: "escribir" },
    { es: "Mañana yo __ a Sevilla.", en: "Tomorrow I will travel to Seville.", fr: "Demain je voyagerai à Séville.", answer: "viajaré", tense: "fut", inf: "viajar" },
    { es: "Ella __ después.", en: "She will eat later.", fr: "Elle mangera plus tard.", answer: "comerá", tense: "fut", inf: "comer" },
    { es: "Nosotros __ allí.", en: "We will live there.", fr: "Nous vivrons là-bas.", answer: "viviremos", tense: "fut", inf: "vivir" },
    { es: "Vosotros __ la tarea.", en: "You all will study the homework.", fr: "Vous étudierez les devoirs.", answer: "estudiaréis", tense: "fut", inf: "estudiar" },
    { es: "Ellos __ temprano.", en: "They will arrive early.", fr: "Ils arriveront tôt.", answer: "llegarán", tense: "fut", inf: "llegar" },
    { es: "Yo __ una carta.", en: "I will write a letter.", fr: "J'écrirai une lettre.", answer: "escribiré", tense: "fut", inf: "escribir" },
    { es: "¿Tú __ pan?", en: "Will you buy bread?", fr: "Tu achèteras du pain ?", answer: "comprarás", tense: "fut", inf: "comprar" },
    { es: "Él __ en la oficina.", en: "He will work in the office.", fr: "Il travaillera au bureau.", answer: "trabajará", tense: "fut", inf: "trabajar" },
    { es: "Yo __ más si tuviera tiempo.", en: "I would travel more if I had time.", fr: "Je voyagerais plus si j'avais le temps.", answer: "viajaría", tense: "cond", inf: "viajar" },
    { es: "¿Tú __ ayudarme?", en: "Would you help me?", fr: "Tu m'aiderais ?", answer: "ayudarías", tense: "cond", inf: "ayudar" },
    { es: "Ella __ aquí.", en: "She would eat here.", fr: "Elle mangerait ici.", answer: "comería", tense: "cond", inf: "comer" },
    { es: "Nosotros __ en la costa.", en: "We would live on the coast.", fr: "Nous vivrions sur la côte.", answer: "viviríamos", tense: "cond", inf: "vivir" },
    { es: "Vosotros __ hoy.", en: "You all would work today.", fr: "Vous travailleriez aujourd'hui.", answer: "trabajaríais", tense: "cond", inf: "trabajar" },
    { es: "Ellos __ temprano.", en: "They would arrive early.", fr: "Ils arriveraient tôt.", answer: "llegarían", tense: "cond", inf: "llegar" },
    { es: "Yo __ la carta.", en: "I would write the letter.", fr: "J'écrirais la lettre.", answer: "escribiría", tense: "cond", inf: "escribir" },
    { es: "¿Tú __ pan?", en: "Would you buy bread?", fr: "Tu achèterais du pain ?", answer: "comprarías", tense: "cond", inf: "comprar" },
    { es: "Yo __ hoy.", en: "I have worked today.", fr: "J'ai travaillé aujourd'hui.", answer: "he trabajado", tense: "presperf", inf: "trabajar" },
    { es: "¿Tú __ ya?", en: "Have you eaten yet?", fr: "Tu as déjà mangé ?", answer: "has comido", tense: "presperf", inf: "comer" },
    { es: "Ella __ mucho.", en: "She has studied a lot.", fr: "Elle a beaucoup étudié.", answer: "ha estudiado", tense: "presperf", inf: "estudiar" },
    { es: "Nosotros __ en Madrid.", en: "We have lived in Madrid.", fr: "Nous avons vécu à Madrid.", answer: "hemos vivido", tense: "presperf", inf: "vivir" },
    { es: "Vosotros __ a Italia.", en: "You all have traveled to Italy.", fr: "Vous avez voyagé en Italie.", answer: "habéis viajado", tense: "presperf", inf: "viajar" },
    { es: "Ellos __ temprano.", en: "They have arrived early.", fr: "Ils sont arrivés tôt.", answer: "han llegado", tense: "presperf", inf: "llegar" },
    { es: "Yo __ pan.", en: "I have bought bread.", fr: "J'ai acheté du pain.", answer: "he comprado", tense: "presperf", inf: "comprar" },
    { es: "Él __ la música.", en: "He has listened to the music.", fr: "Il a écouté la musique.", answer: "ha escuchado", tense: "presperf", inf: "escuchar" },
    { es: "Yo __ cuando llegaste.", en: "I had studied when you arrived.", fr: "J'avais étudié quand tu es arrivé.", answer: "había estudiado", tense: "plup", inf: "estudiar" },
    { es: "Ella __ antes de salir.", en: "She had eaten before leaving.", fr: "Elle avait mangé avant de partir.", answer: "había comido", tense: "plup", inf: "comer" },
    { es: "Nosotros __ allí dos años.", en: "We had lived there for two years.", fr: "Nous avions vécu là-bas pendant deux ans.", answer: "habíamos vivido", tense: "plup", inf: "vivir" },
    { es: "Vosotros __ a tiempo.", en: "You all had arrived on time.", fr: "Vous étiez arrivés à l'heure.", answer: "habíais llegado", tense: "plup", inf: "llegar" },
    { es: "Ellos __ mucho.", en: "They had worked a lot.", fr: "Ils avaient beaucoup travaillé.", answer: "habían trabajado", tense: "plup", inf: "trabajar" },
    { es: "Yo __ a México.", en: "I had traveled to Mexico.", fr: "J'avais voyagé au Mexique.", answer: "había viajado", tense: "plup", inf: "viajar" },
    { es: "¿Tú __ ya?", en: "Had you drunk already?", fr: "Tu avais déjà bu ?", answer: "habías bebido", tense: "plup", inf: "beber" },
    { es: "Él __ la música.", en: "He had listened to the music.", fr: "Il avait écouté la musique.", answer: "había escuchado", tense: "plup", inf: "escuchar" },
    { es: "Para mañana yo __ el examen.", en: "By tomorrow I will have studied for the exam.", fr: "D'ici demain j'aurai étudié pour l'examen.", answer: "habré estudiado", tense: "futperf", inf: "estudiar" },
    { es: "¿Tú __ antes de llegar?", en: "Will you have eaten before arriving?", fr: "Tu auras mangé avant d'arriver ?", answer: "habrás comido", tense: "futperf", inf: "comer" },
    { es: "Ella __ allí diez años.", en: "She will have lived there ten years.", fr: "Elle aura vécu là-bas dix ans.", answer: "habrá vivido", tense: "futperf", inf: "vivir" },
    { es: "Nosotros __ suficiente.", en: "We will have studied enough.", fr: "Nous aurons assez étudié.", answer: "habremos estudiado", tense: "futperf", inf: "estudiar" },
    { es: "Vosotros __ temprano.", en: "You all will have arrived early.", fr: "Vous serez arrivés tôt.", answer: "habréis llegado", tense: "futperf", inf: "llegar" },
    { es: "Ellos __ la casa.", en: "They will have bought the house.", fr: "Ils auront acheté la maison.", answer: "habrán comprado", tense: "futperf", inf: "comprar" },
    { es: "Yo __ mucho.", en: "I will have traveled a lot.", fr: "J'aurai beaucoup voyagé.", answer: "habré viajado", tense: "futperf", inf: "viajar" },
    { es: "Él __ agua.", en: "He will have drunk water.", fr: "Il aura bu de l'eau.", answer: "habrá bebido", tense: "futperf", inf: "beber" },
    { es: "Yo __ pero estaba enfermo.", en: "I would have traveled but I was sick.", fr: "J'aurais voyagé mais j'étais malade.", answer: "habría viajado", tense: "condperf", inf: "viajar" },
    { es: "¿Tú __ más?", en: "Would you have eaten more?", fr: "Tu aurais mangé plus ?", answer: "habrías comido", tense: "condperf", inf: "comer" },
    { es: "Ella __ allí.", en: "She would have lived there.", fr: "Elle aurait vécu là-bas.", answer: "habría vivido", tense: "condperf", inf: "vivir" },
    { es: "Nosotros __ antes.", en: "We would have studied earlier.", fr: "Nous aurions étudié plus tôt.", answer: "habríamos estudiado", tense: "condperf", inf: "estudiar" },
    { es: "Vosotros __ temprano.", en: "You all would have arrived early.", fr: "Vous seriez arrivés tôt.", answer: "habríais llegado", tense: "condperf", inf: "llegar" },
    { es: "Ellos __ la casa.", en: "They would have bought the house.", fr: "Ils auraient acheté la maison.", answer: "habrían comprado", tense: "condperf", inf: "comprar" },
    { es: "Yo __ mucho.", en: "I would have worked a lot.", fr: "J'aurais beaucoup travaillé.", answer: "habría trabajado", tense: "condperf", inf: "trabajar" },
    { es: "Él __ la música.", en: "He would have listened to the music.", fr: "Il aurait écouté la musique.", answer: "habría escuchado", tense: "condperf", inf: "escuchar" },
    { es: "Espero que tú __.", en: "I hope you study.", fr: "J'espère que tu étudies.", answer: "estudies", tense: "subpres", inf: "estudiar" },
    { es: "Es posible que él __ aquí.", en: "It's possible that he eats here.", fr: "Il est possible qu'il mange ici.", answer: "coma", tense: "subpres", inf: "comer" },
    { es: "Quiero que nosotros __ juntos.", en: "I want us to live together.", fr: "Je veux que nous vivions ensemble.", answer: "vivamos", tense: "subpres", inf: "vivir" },
    { es: "Dudo que ellos __ tarde.", en: "I doubt they arrive late.", fr: "Je doute qu'ils arrivent en retard.", answer: "lleguen", tense: "subpres", inf: "llegar" },
    { es: "Ojalá tú __ hoy.", en: "Hopefully you work today.", fr: "J'espère que tu travailles aujourd'hui.", answer: "trabajes", tense: "subpres", inf: "trabajar" },
    { es: "Recomiendo que vosotros __ más.", en: "I recommend you all study more.", fr: "Je recommande que vous étudiiez plus.", answer: "estudiéis", tense: "subpres", inf: "estudiar" },
    { es: "Es bueno que ella __ la carta.", en: "It's good that she writes the letter.", fr: "C'est bien qu'elle écrive la lettre.", answer: "escriba", tense: "subpres", inf: "escribir" },
    { es: "Quería que tú __.", en: "I wanted you to study.", fr: "Je voulais que tu études.", answer: "estudiaras", tense: "subimp", inf: "estudiar" },
    { es: "Si yo __ tiempo, estudiara más.", en: "If I worked, I would study more.", fr: "Si je travaillais, j'étudierais plus.", answer: "trabajara", tense: "subimp", inf: "trabajar" },
    { es: "Era importante que él __.", en: "It was important that he eat.", fr: "Il était important qu'il mange.", answer: "comiera", tense: "subimp", inf: "comer" },
    { es: "Dudaban que nosotros __ allí.", en: "They doubted we lived there.", fr: "Ils doutaient que nous vivions là-bas.", answer: "viviéramos", tense: "subimp", inf: "vivir" },
    { es: "Ojalá yo __ hoy.", en: "I wish I worked today.", fr: "J'aimerais travailler aujourd'hui.", answer: "trabajara", tense: "subimp", inf: "trabajar" },
    { es: "Recomendé que vosotros __.", en: "I recommended that you all arrive.", fr: "J'ai recommandé que vous arriviez.", answer: "llegarais", tense: "subimp", inf: "llegar" },
    { es: "Quería que ella __.", en: "I wanted her to write.", fr: "Je voulais qu'elle écrive.", answer: "escribiera", tense: "subimp", inf: "escribir" },
    { es: "Me alegra que tú __.", en: "I'm glad you have arrived.", fr: "Je suis content que tu sois arrivé.", answer: "hayas llegado", tense: "subperf", inf: "llegar" },
    { es: "Es posible que él __.", en: "It's possible he has eaten.", fr: "Il est possible qu'il ait mangé.", answer: "haya comido", tense: "subperf", inf: "comer" },
    { es: "Dudo que ellos __.", en: "I doubt they have lived there.", fr: "Je doute qu'ils aient vécu là-bas.", answer: "hayan vivido", tense: "subperf", inf: "vivir" },
    { es: "Espero que vosotros __.", en: "I hope you all have studied.", fr: "J'espère que vous ayez étudié.", answer: "hayáis estudiado", tense: "subperf", inf: "estudiar" },
    { es: "No creo que ella __.", en: "I don't think she has worked.", fr: "Je ne crois pas qu'elle ait travaillé.", answer: "haya trabajado", tense: "subperf", inf: "trabajar" },
    { es: "Es bueno que nosotros __.", en: "It's good that we have traveled.", fr: "C'est bien que nous ayons voyagé.", answer: "hayamos viajado", tense: "subperf", inf: "viajar" },
    { es: "Me sorprende que tú __.", en: "It surprises me that you have drunk.", fr: "Cela me surprend que tu aies bu.", answer: "hayas bebido", tense: "subperf", inf: "beber" },
    { es: "Me alegró que tú __.", en: "I was glad you had arrived.", fr: "J'étais content que tu sois arrivé.", answer: "hubieras llegado", tense: "subplup", inf: "llegar" },
    { es: "Si nosotros __, habríamos aprobado.", en: "If we had studied, we would have passed.", fr: "Si nous avions étudié, nous aurions réussi.", answer: "hubiéramos estudiado", tense: "subplup", inf: "estudiar" },
    { es: "Dudaba que él __.", en: "I doubted he had eaten.", fr: "Je doutais qu'il ait mangé.", answer: "hubiera comido", tense: "subplup", inf: "comer" },
    { es: "Ojalá vosotros __ allí.", en: "I wish you all had lived there.", fr: "J'aurais aimé que vous ayez vécu là-bas.", answer: "hubierais vivido", tense: "subplup", inf: "vivir" },
    { es: "No creían que ella __.", en: "They didn't believe she had worked.", fr: "Ils ne croyaient pas qu'elle ait travaillé.", answer: "hubiera trabajado", tense: "subplup", inf: "trabajar" },
    { es: "Era posible que yo __.", en: "It was possible that I had traveled.", fr: "Il était possible que j'aie voyagé.", answer: "hubiera viajado", tense: "subplup", inf: "viajar" },
    { es: "Me molestó que ellos __.", en: "It bothered me that they had arrived.", fr: "Cela m'a dérangé qu'ils soient arrivés.", answer: "hubieran llegado", tense: "subplup", inf: "llegar" }
  ];
  //export default baseQuestions;