import { NextResponse } from 'next/server';

export type Tense = {
  id: string;
  name: string;
  level: string;
  desc: string;
  endings: {
    ar: string[];
    er: string[];
    ir: string[];
  };
  examples: [string, string][];
};

const tenseKeys = ["pres", "pret", "imp", "fut", "cond", "presperf", "plup", "futperf", "condperf", "subpres", "subimp", "subperf", "subplup"];

export const tenseMap: Record<string, string> = {
  pres: "Presente",
  pret: "Pretérito",
  imp: "Imperfecto",
  fut: "Futuro",
  cond: "Condicional",
  presperf: "Pretérito perfecto",
  plup: "Pluscuamperfecto",
  futperf: "Futuro perfecto",
  condperf: "Condicional perfecto",
  subpres: "Subjuntivo",
  subimp: "Subjuntivo imperfecto",
  subperf: "Subjuntivo perfecto",
  subplup: "Subjuntivo pluscuamperfecto",
};

const tenses: Tense[] = [
  { id: "pres", name: "Presente", level: "A1", desc: "Habits, general truths, current actions.", endings: { ar: ["-o", "-as", "-a", "-amos", "-áis", "-an"], er: ["-o", "-es", "-e", "-emos", "-éis", "-en"], ir: ["-o", "-es", "-e", "-imos", "-ís", "-en"] }, examples: [["El sol sale por el este cada mañana.", "The sun rises in the east every morning."], ["Mi hermana trabaja como médica en un hospital.", "My sister works as a doctor in a hospital."], ["¿Qué haces los fines de semana?", "What do you do on weekends?"], ["Los niños juegan en el parque ahora mismo.", "The children are playing in the park right now."], ["Nunca bebo café después de las seis.", "I never drink coffee after six."]] },
  { id: "pret", name: "Pretérito", level: "A2", desc: "Completed actions in the past.", endings: { ar: ["-é", "-aste", "-ó", "-amos", "-asteis", "-aron"], er: ["-í", "-iste", "-ió", "-imos", "-isteis", "-ieron"], ir: ["-í", "-iste", "-ió", "-imos", "-isteis", "-ieron"] }, examples: [["El año pasado viajé a Japón por primera vez.", "Last year I traveled to Japan for the first time."], ["María rompió su teléfono cuando se cayó.", "María broke her phone when she fell."], ["¿Cuándo conociste a tu mejor amigo?", "When did you meet your best friend?"], ["Los estudiantes escribieron un ensayo completo en una hora.", "The students wrote a complete essay in one hour."], ["Ayer por la noche llovió intensamente.", "Last night it rained heavily."]] },
  { id: "imp", name: "Imperfecto", level: "A2", desc: "Ongoing/repeated past actions; descriptions.", endings: { ar: ["-aba", "-abas", "-aba", "-ábamos", "-abais", "-aban"], er: ["-ía", "-ías", "-ía", "-íamos", "-íais", "-ían"], ir: ["-ía", "-ías", "-ía", "-íamos", "-íais", "-ían"] }, examples: [["Cuando tenía veinte años, estudiaba arquitectura en la universidad.", "When I was twenty, I was studying architecture at university."], ["Mi abuela siempre cocinaba los domingos para toda la familia.", "My grandmother always cooked on Sundays for the whole family."], ["El cielo estaba nublado y hacía mucho frío.", "The sky was cloudy and it was very cold."], ["De pequeño, leía un libro cada semana.", "As a child, I used to read a book every week."], ["Mientras caminábamos, veíamos las estrellas brillar.", "While we were walking, we saw the stars shining."]] },
  { id: "fut", name: "Futuro", level: "B1", desc: "Future actions; probability.", endings: { ar: ["-aré", "-arás", "-ará", "-aremos", "-aréis", "-arán"], er: ["-eré", "-erás", "-erá", "-eremos", "-eréis", "-erán"], ir: ["-iré", "-irás", "-irá", "-iremos", "-iréis", "-irán"] }, examples: [["El próximo verano visitaré las ruinas de Machu Picchu.", "Next summer I will visit the ruins of Machu Picchu."], ["¿Crees que lloverá durante la boda?", "Do you think it will rain during the wedding?"], ["En cinco años, probablemente viviré en otro país.", "In five years, I will probably live in another country."], ["Serán las tres de la tarde cuando llegues.", "It's probably three in the afternoon when you arrive."], ["Prometo que te llamaré cuando aterrice el avión.", "I promise I will call you when the plane lands."]] },
  { id: "cond", name: "Condicional", level: "B1", desc: "Polite requests; hypothetical situations.", endings: { ar: ["-aría", "-arías", "-aría", "-aríamos", "-aríais", "-arían"], er: ["-ería", "-erías", "-ería", "-eríamos", "-eríais", "-erían"], ir: ["-iría", "-irías", "-iría", "-iríamos", "-iríais", "-irían"] }, examples: [["¿Podrías pasarme la sal, por favor?", "Could you pass me the salt, please?"], ["Si ganara la lotería, compraría una casa en la playa.", "If I won the lottery, I would buy a house on the beach."], ["Me encantaría acompañarte al concierto, pero tengo otros planes.", "I would love to accompany you to the concert, but I have other plans."], ["¿Qué harías tú en mi situación?", "What would you do in my situation?"], ["Sería ideal si pudieras llegar un poco más temprano.", "It would be ideal if you could arrive a bit earlier."]] },
  { id: "presperf", name: "Pretérito perfecto", level: "B1", desc: "Past actions connected to the present.", endings: { ar: ["he -ado", "has -ado", "ha -ado", "hemos -ado", "habéis -ado", "han -ado"], er: ["he -ido", "has -ido", "ha -ido", "hemos -ido", "habéis -ido", "han -ido"], ir: ["he -ido", "has -ido", "ha -ido", "hemos -ido", "habéis -ido", "han -ido"] }, examples: [["Esta semana he aprendido diez palabras nuevas en francés.", "This week I have learned ten new words in French."], ["¿Has visto la nueva película de Almodóvar?", "Have you seen Almodóvar's new movie?"], ["Nunca he probado la comida tailandesa, pero me encantaría.", "I have never tried Thai food, but I would love to."], ["Los científicos han descubierto una nueva especie de mariposa.", "Scientists have discovered a new species of butterfly."], ["Hemos estado esperando aquí durante más de una hora.", "We have been waiting here for more than an hour."]] },
  { id: "plup", name: "Pluscuamperfecto", level: "B2", desc: "Actions completed before another past action.", endings: { ar: ["había -ado", "habías -ado", "había -ado", "habíamos -ado", "habíais -ado", "habían -ado"], er: ["había -ido", "habías -ido", "había -ido", "habíamos -ido", "habíais -ido", "habían -ido"], ir: ["había -ido", "habías -ido", "había -ido", "habíamos -ido", "habíais -ido", "habían -ido"] }, examples: [["Cuando llegué a la estación, el tren ya había salido.", "When I arrived at the station, the train had already left."], ["Ella había vivido en París durante tres años antes de mudarse a Madrid.", "She had lived in Paris for three years before moving to Madrid."], ["¿Habías estado alguna vez en ese restaurante antes de ayer?", "Had you ever been to that restaurant before yesterday?"], ["Los ladrones habían robado el banco antes de que sonara la alarma.", "The thieves had robbed the bank before the alarm went off."], ["Me di cuenta de que había olvidado mi cartera en casa.", "I realized that I had forgotten my wallet at home."]] },
  { id: "futperf", name: "Futuro perfecto", level: "B2", desc: "Something that will have happened by a future time.", endings: { ar: ["habré -ado", "habrás -ado", "habrá -ado", "habremos -ado", "habréis -ado", "habrán -ado"], er: ["habré -ido", "habrás -ido", "habrá -ido", "habremos -ido", "habréis -ido", "habrán -ido"], ir: ["habré -ido", "habrás -ido", "habrá -ido", "habremos -ido", "habréis -ido", "habrán -ido"] }, examples: [["Para cuando llegues, ya habré terminado de preparar la cena.", "By the time you arrive, I will have finished preparing dinner."], ["El próximo mes habremos estado casados durante veinte años.", "Next month we will have been married for twenty years."], ["¿Habrás completado el proyecto antes del viernes?", "Will you have completed the project before Friday?"], ["Para el año 2030, los científicos habrán desarrollado una cura para esa enfermedad.", "By the year 2030, scientists will have developed a cure for that disease."], ["Cuando cumpla treinta años, habré visitado más de cuarenta países.", "When I turn thirty, I will have visited more than forty countries."]] },
  { id: "condperf", name: "Condicional perfecto", level: "B2", desc: "What would have happened.", endings: { ar: ["habría -ado", "habrías -ado", "habría -ado", "habríamos -ado", "habríais -ado", "habrían -ado"], er: ["habría -ido", "habrías -ido", "habría -ido", "habríamos -ido", "habríais -ido", "habrían -ido"], ir: ["habría -ido", "habrías -ido", "habría -ido", "habríamos -ido", "habríais -ido", "habrían -ido"] }, examples: [["Habría llamado antes, pero mi teléfono se quedó sin batería.", "I would have called earlier, but my phone ran out of battery."], ["Si hubieras estudiado más, habrías aprobado el examen sin problemas.", "If you had studied more, you would have passed the exam without problems."], ["¿Habrías aceptado el trabajo si te hubieran ofrecido más dinero?", "Would you have accepted the job if they had offered you more money?"], ["Nunca habríamos imaginado que el concierto sería tan increíble.", "We would never have imagined that the concert would be so incredible."], ["Ella habría venido a la fiesta, pero tenía que trabajar esa noche.", "She would have come to the party, but she had to work that night."]] },
  { id: "subpres", name: "Subjuntivo", level: "B1", desc: "Wishes, doubts, recommendations in present/future.", endings: { ar: ["-e", "-es", "-e", "-emos", "-éis", "-en"], er: ["-a", "-as", "-a", "-amos", "-áis", "-an"], ir: ["-a", "-as", "-a", "-amos", "-áis", "-an"] }, examples: [["Espero que encuentres un buen trabajo pronto.", "I hope you find a good job soon."], ["No creo que ella tenga razón en este asunto.", "I don't think she is right about this matter."], ["Es importante que los niños duerman al menos ocho horas.", "It's important that children sleep at least eight hours."], ["Dudo que el equipo gane el campeonato este año.", "I doubt the team will win the championship this year."], ["Ojalá que el tiempo mejore para el fin de semana.", "I hope the weather improves for the weekend."]] },
  { id: "subimp", name: "Subjuntivo imperfecto", level: "B2", desc: "Wishes/doubts in the past; after conditional.", endings: { ar: ["-ara", "-aras", "-ara", "-áramos", "-arais", "-aran"], er: ["-iera", "-ieras", "-iera", "-iéramos", "-ierais", "-ieran"], ir: ["-iera", "-ieras", "-iera", "-iéramos", "-ierais", "-ieran"] }, examples: [["Mi madre quería que yo estudiara medicina en lugar de arte.", "My mother wanted me to study medicine instead of art."], ["Si tuviera más tiempo libre, viajara por todo el mundo.", "If I had more free time, I would travel around the world."], ["Era necesario que todos los estudiantes entregaran el ensayo ayer.", "It was necessary that all students turn in the essay yesterday."], ["Ojalá que lloviera más en esta región durante el verano.", "I wish it would rain more in this region during the summer."], ["Dudaban que el proyecto fuera exitoso sin más financiamiento.", "They doubted the project would be successful without more funding."]] },
  { id: "subperf", name: "Subjuntivo perfecto", level: "B2", desc: "Subjunctive with completed action linked to present.", endings: { ar: ["haya -ado", "hayas -ado", "haya -ado", "hayamos -ado", "hayáis -ado", "hayan -ado"], er: ["haya -ido", "hayas -ido", "haya -ido", "hayamos -ido", "hayáis -ido", "hayan -ido"], ir: ["haya -ido", "hayas -ido", "haya -ido", "hayamos -ido", "hayáis -ido", "hayan -ido"] }, examples: [["Me sorprende que hayas terminado el proyecto tan rápido.", "It surprises me that you have finished the project so quickly."], ["No es posible que él haya llegado ya; el vuelo sale en una hora.", "It's not possible that he has already arrived; the flight leaves in an hour."], ["Espero que hayan disfrutado de la conferencia tanto como yo.", "I hope they have enjoyed the conference as much as I have."], ["Dudo que hayamos tomado la decisión correcta en esta situación.", "I doubt we have made the right decision in this situation."], ["Ojalá que hayas encontrado lo que buscabas en la biblioteca.", "I hope you have found what you were looking for in the library."]] },
  { id: "subplup", name: "Subjuntivo pluscuamperfecto", level: "C1", desc: "Subjunctive with completed action prior to a past reference.", endings: { ar: ["hubiera -ado", "hubieras -ado", "hubiera -ado", "hubiéramos -ado", "hubierais -ado", "hubieran -ado"], er: ["hubiera -ido", "hubieras -ido", "hubiera -ido", "hubiéramos -ido", "hubierais -ido", "hubieran -ido"], ir: ["hubiera -ido", "hubieras -ido", "hubiera -ido", "hubiéramos -ido", "hubierais -ido", "hubieran -ido"] }, examples: [["Me habría encantado que hubieras venido a mi graduación.", "I would have loved for you to have come to my graduation."], ["Si hubiéramos sabido la verdad antes, habríamos actuado de manera diferente.", "If we had known the truth earlier, we would have acted differently."], ["Era imposible que ellos hubieran completado el trabajo sin ayuda.", "It was impossible that they had completed the work without help."], ["Ojalá que hubieras estado allí para ver el atardecer; fue espectacular.", "I wish you had been there to see the sunset; it was spectacular."], ["No creían que el equipo hubiera ganado el partido sin su mejor jugador.", "They didn't believe the team had won the match without their best player."]] }
];

export async function GET() {
  // This is a stub that returns the static tenses array.
  // Eventually, this could be populated by calls to a large language model.
  return NextResponse.json(tenses);
}
